version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
